/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import javax.swing.JFrame;
import javax.swing.JPanel;
import org.w3c.dom.events.MouseEvent;

/**
 *
 * @author stephen
 */
public class MainFrame extends javax.swing.JFrame{

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        initComponentsCustom();
        //draw in panelDraw
        graphics = PanelDraw.getGraphics();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        try {
            PanelDraw =(javax.swing.JPanel)java.beans.Beans.instantiate(getClass().getClassLoader(), "test.MainFrame_PanelDraw");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        jPanel2 = new javax.swing.JPanel();
        btnShapeRectangle = new javax.swing.JButton();
        btnShapeCircle = new javax.swing.JButton();
        btnShapeTriangle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout PanelDrawLayout = new javax.swing.GroupLayout(PanelDraw);
        PanelDraw.setLayout(PanelDrawLayout);
        PanelDrawLayout.setHorizontalGroup(
            PanelDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );
        PanelDrawLayout.setVerticalGroup(
            PanelDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        jPanel2.setBackground(java.awt.Color.lightGray);

        btnShapeRectangle.setText("Rectangle");
        btnShapeRectangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShapeRectangleActionPerformed(evt);
            }
        });

        btnShapeCircle.setText("Circle");
        btnShapeCircle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShapeCircleActionPerformed(evt);
            }
        });

        btnShapeTriangle.setText("Triangle");
        btnShapeTriangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShapeTriangleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnShapeRectangle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnShapeCircle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnShapeTriangle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnShapeRectangle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnShapeCircle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnShapeTriangle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelDraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelDraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShapeRectangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShapeRectangleActionPerformed
        // TODO add your handling code here:
        setShape("rectangle");
    }//GEN-LAST:event_btnShapeRectangleActionPerformed

    private void btnShapeCircleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShapeCircleActionPerformed
        // TODO add your handling code here:
        setShape("circle");
    }//GEN-LAST:event_btnShapeCircleActionPerformed

    private void btnShapeTriangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShapeTriangleActionPerformed
        // TODO add your handling code here:
        setShape("triangle");
    }//GEN-LAST:event_btnShapeTriangleActionPerformed

    private void setShape(String Shape) {
        shape = Shape;
        switch (Shape) {
            case "rectangle":

                break;
            case "cricle":

                break;
            case "triangle":

                break;

        }
    }

    private void draw(String Shape, int PositionX, int PositionY, int width, int length, Color Clr, boolean fill) {
        graphics.setColor(Clr);
        switch (Shape) {
            case "rectangle":
                if (fill) {
                    graphics.fillRect(PositionX, PositionY, width, length);
                }
                break;
            case "cricle":
                graphics.fillOval(PositionX, PositionY, width, length);
                break;
            case "triangle":
//                    graphics.fill
                break;

        }
        graphics.dispose();
    }
    //shape manager
    String shape = "rectangle";//default shape is rectangle
    //graphic use draw 
    Graphics graphics;
    int shapePositionX;
    int shapePositionY;
    int shapeWidth = 100;
    int shapeLenght = 100;
    Color shapeColor = Color.BLACK;
    boolean shapeFill = true;
    static JFrame mainFrame;
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                mainFrame = new MainFrame();
                mainFrame.setVisible(true);

            }
        });
    }

    private void initComponentsCustom() {
        panelDraw = new PanelDraw();
        panelDraw.setSize(600, 500);
        mainFrame.add(panelDraw);
    }

    private class panelDraw extends JPanel implements MouseListener, MouseMotionListener {

        private panelDraw() {

            addMouseListener(this);
            addMouseMotionListener(this);
        }

        @Override
        public void mouseClicked(java.awt.event.MouseEvent me) {
            System.out.println("click");
            shapePositionX = me.getX();
            shapePositionY = me.getY();
            draw(shape, shapePositionX, shapePositionY, shapeWidth, shapeLenght, shapeColor, shapeFill);
        }

        @Override
        public void mousePressed(java.awt.event.MouseEvent me) {
        }

        @Override
        public void mouseReleased(java.awt.event.MouseEvent me) {
        }

        @Override
        public void mouseEntered(java.awt.event.MouseEvent me) {
        }

        @Override
        public void mouseExited(java.awt.event.MouseEvent me) {
        }

        @Override
        public void mouseDragged(java.awt.event.MouseEvent me) {
        }

        @Override
        public void mouseMoved(java.awt.event.MouseEvent me) {
        }
    }
    
    private JPanel panelDraw;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDraw;
    private javax.swing.JButton btnShapeCircle;
    private javax.swing.JButton btnShapeRectangle;
    private javax.swing.JButton btnShapeTriangle;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
